name: Platformer Generated gig-scripts-prod Build
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/lsflk/gig-scripts
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_D04C39CB_A9FF_4E2C_87A0_9C637B19A2F7 }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:prod-${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:prod-${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_D861FCF5_CBE3_4D87_A3ED_DF46C3998D5A}}
          project-id: ${{secrets.PROJECT_ID_D861FCF5_CBE3_4D87_A3ED_DF46C3998D5A}}
          token: ${{secrets.AUTOGENERATED_CICD_D861FCF5_CBE3_4D87_A3ED_DF46C3998D5A}}
          image-name: ${{env.SERVICE_NAME}}
          tag: prod-${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: ac9bbf21-a084-4622-a2e2-e17e5714ea03
